site_name: 'Flask-MongoDB'
site_description: 'A Flask extension for connecting to a MongoDB instance'
repo_url: https://github.com/juanmanuel96/flask-mongodb

nav:
  - Home : index.md
  - Database Operations:
    - The MongoDB Class: mongo.md
    - Models: collections.md
  - Data Validation:
    - Serializing Data: serializers.md
  - CLI Tool:
    - flask-mongodb: cli.md
  - API Refrence:
    - API Reference: api.md
  - Changelog:
    - Changelog: changelog.md

theme:
  name: readthedocs

extra_css: 
  - stylesheet/extra.css

extra: 
  pkg_version: v1.8.0
  version: v1.8.x

plugins:
  - search
  - markdownextradata
  - mike
